name = 'Ikigai'
license = 'GNU GPLv3'
licenselink = 'https://github.com/dancs-dev/ikigai/COPYING'
description = 'A simple Hugo theme.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/dancs-dev/ikigai'

# If you have a running demo of the theme
demosite = ''

# Taxonomy terms
# tags = ['blog', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has multiple authors
# authors = [
#   {name = 'Name of author', homepage = 'Website of author'},
#   {name = 'Name of author', homepage = 'Website of author'}
# ]

# If the theme has a single author
[author]
  name = 'dancs-dev'
  homepage = 'https://dancs.dev'
